### ISSUE TITLE
Available sensors in Home Assistant

### ISSUE THREAD

**Issue by morhimi** [OnFreund/pyrympro#2]
Hi,

thanks for this project, I tried adding ti to HA and the only available sensor is `Total consumption` while I see in the code that `v0.0.7` has support for daily and monthly consumption.

any idea what's needed in order to support these as sensors in HA as well?

**Comment by OnFreund** [comment]
This library currently provides a total consumption and a monthly forecast. You might be confusing it with the custom integration.
In any case, you can easily create daily and monthly consumption sensors based on the total consumption using the [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/) integration.
